name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy: 
      matrix:
        php: [7.4, 8.0, 8.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build --build-arg PHP=${{ matrix.php }} . --file Dockerfile --tag tinect/shopware-easy-coding-standard:php${{ matrix.php }}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tinect/shopware-easy-coding-standard
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
