name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy: 
      matrix:
        php: [7.4, 8.0, 8.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build --build-arg PHP_VERSION=${{ matrix.php }} . --file Dockerfile --tag tinect/shopware-easy-coding-standard:${{ matrix.php }}

      - name: Get Tag
        id: get-publish-docker-tags
        run: |
          if [[ "${{ matrix.php }}" == "8.1" ]]; then
            tags="${{ matrix.php }},latest"
          else
            tags="${{ matrix.php }}"
          fi
          echo "::set-output name=tag::${tags}"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tinect/shopware-easy-coding-standard
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.get-publish-docker-tags.outputs.tags }}
